### ISSUE TITLE
question: v0.8.0 vs v0.8.1

### ISSUE THREAD

**Issue by greut** [erusev/parsedown-extra#145]
Hey @erusev and @aidantwoods 

Why do the 0.8.0 and 0.8.1 versions look so different (from the packagist point of view)?

**Comment by aidantwoods** [comment]
0.8.0 was meant to resolve some issues with PHP 7.4 comparability, but was released from a version of the codebase which was designed for the Parsedown 1.8.0-beta series. This means that using 0.8.0 would require using a beta version of the Parsedown core class which would cause installation issues where minimum stability is enforced.
After [gearing up for 1.8](https://github.com/erusev/parsedown/issues/601) it became evident that the way in which extensions utilise Parsedown lacks a clear interface definition, meaning it is unclear which internal behaviours can be changed without causing breakage. Hence Parsedown 1.8 hasn't been released and Parsedown-Extra 0.8.0, which was meant to be a bug fix release, shouldn't be depending on this version. 

0.8.1 branches only slightly upstream from the previous 0.7.1 release, and brings the fixes from 0.8.0 without the potential breakage (hence looks a bit different because it doesn't include a lot of mistakenly included new code).

**Comment by greut** [comment]
@aidantwoods cool, then I'll use the 0.8.1 waiting for the 1.8 to be finalize. Thanks for all the work.
